name: Docker Image CI

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker Image
      run: docker pull ichsan060501/testing-aws:latest
    - name: Delete old container
      run: docker rm -f ichsan060501/testing-aws || true
    - name: Run Docker Container
      run: docker run -d -p 80:80 --name ichsan060501/testing-aws ichsan060501/testing-aws:latest
